# Define the stages that will be executed in order
stages:
  - deploy

# Job: Run git pull and other commands directly on the server
deploy_job:
  stage: deploy
  image: php:8.2-cli

  script:
    - apt-get update && apt-get install -y git unzip nodejs npm
    - cd /home/xpertsmy/public_html/evlease.xperts.my
    - git reset --hard
    - git pull origin main
    - composer install --no-dev --optimize-autoloader --ignore-platform-reqs
    - php artisan migrate --force
    - php artisan optimize:clear
    - npm install
    - npm run build

  only:
    - main